version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f docker/Dockerfile.app -t georgelima/app-samu .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
